### PR TITLE
Misc refactorings

### PR DESCRIPTION
**Pull request by sunfishcode**
This eliminates the dependency on rust-errno, and introduces a `create_file` utility function, since multiple tests can use it.

### CODE REVIEW

**Comment by kubkon** [comment]
Also, am I correct to assume that the crate can be built using stable toolchain with this change? If that’s the case, I’ve started to wonder whether it wouldn’t be easier to have the test cases pulled into `wasi-common` as a submodule and built on the fly. This would help with test synchronisation which effects I’ve been experiencing more and more these days: impl some new functionality in WASI, add matching test case, push binary to `wasi-common`, oh and remember to push the sources here. If there’s a couple of things going on at once, it’s easy to lose track and forget which binary corresponds to which version of the testcase’s source. Some food for thought!

**Comment by sunfishcode** [comment]
Yes; I just did a build with the stable toolchain, and everything passed.

And yeah, I agree our current repo organization isn't ideal, and am open to ideas :-).

**Comment by sunfishcode** [comment]
I've now updated the readlink test.

**Comment by kubkon** [comment]
> Yes; I just did a build with the stable toolchain, and everything passed.
> 
> And yeah, I agree our current repo organization isn't ideal, and am open to ideas :-).

Cool! I’ll post an issue with a proposition then when it clarifies in my head! :-)

**Pull request merged**
